[package]
name = "get-socks-change-file"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.15"
serde = {  version = "1.0.219", features = ["serde_derive", "derive"] }
serde_yaml = "0.9.34"
tokio = "1.45.0"
