proxy_sources:
  - socks_list_url: http://127.0.0.1:1081
    get_list_proxy: socks5://127.0.0.1:1082
  - socks_list_url: http://127.0.0.1:1081
    get_list_proxy: socks5://127.0.0.1:1082
check_url: 'https://kunkka.proxy/test'
check_host: 'kunkka.proxy'
host_dns: ''
timeout: 2
target_path: ./target_path
target_start: target_start