proxy_sources:
  - socks_list_url: http://127.0.0.1:1081
    get_list_proxy: http://127.0.0.1:1082
  - socks_list_url: http://127.0.0.1:1081
    get_list_proxy: http://127.0.0.1:1082
cert_path: './'
