name: Build Release
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: false
jobs:
  getbin:
    name: build ${{ matrix.target }} ${{ inputs.version }}
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
    runs-on: ${{matrix.os}}
    env:
      DIST_DIR: get-socks-${{ matrix.target }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Rust Toolchain Components
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - name: Install cross
        uses: taiki-e/install-action@v2
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          tool: cross
      - name: Build
        run: cross build  --release --target=${{ matrix.target }}
      - name: Say Hello
        run: echo "Hello, World!"
      - name: Upload file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: target/${{ matrix.target }}/release/get-socks-change-file
          retention-days: 30
