name: Build Release
on:
  workflow_dispatch:

jobs:
  getbin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Say Hello
        run: echo "Hello, World!"
        
      - name: Print date
        run: echo "Current date: $(date)"
        
      - name: Print environment
        run: echo "Running on: ${{ runner.os }}"
